### ISSUE TITLE
Farmer dashboard not showing data

### ISSUE THREAD

**Issue by elhenriq** [precision-sustainable-ag/on-farm-dashboard#14]
A grower (Nathan Lowder) that has been with us multiple years is contacting me to see his data. I directed him to the farmer dashboard but  quickly realize that wasn't good because there is almost no data showing regarding yield and biomass and for the identification of the fields on water view it's not coming up either. what should we do about this?

**Comment by screberg** [comment]
Esleyther, can you check on his sites again. There has been a lot more parsing since this issue was started.

**Comment by elhenriq** [comment]
i see a lot more data now. thanks
